version: '3.9'
services:
  fastapi:
    build:
      context: ./
      dockerfile: Dockerfile.api 
    container_name: fastapi
    ports:
      - 80:5000
    volumes:
      - ./sdxcrypto:/app/sdxcrypto
  frontend:
    build:
      context: ./
      dockerfile: Dockerfile.streamlit 
    container_name: frontend
    ports:
      - 8501:8501
    volumes:
      - ./sdxcrypto:/app/sdxcrypto


