version: '3.9'
services:
  fastapi:
    build:
      context: ./
      dockerfile: api.Dockerfile
    container_name: fastapi
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    ports:
      - 80:5000
    volumes:
      - ./sdxcrypto:/app/sdxcrypto
  frontend:
    build:
      context: ./
      dockerfile: streamlit.Dockerfile 
    container_name: frontend
    ports:
      - 8501:8501
    volumes:
      - ./sdxcrypto:/app/sdxcrypto