FROM pytorch/pytorch:1.12.1-cuda11.3-cudnn8-runtime

WORKDIR /app

COPY . .

RUN pip install -e .

EXPOSE 5000

CMD ["uvicorn", "sdxcrypto.main:app", "--reload", "--host", "0.0.0.0", "--port", "5000"]
